services:
  backend:
    container_name: my-backend-container
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=my-postgres-container
      - DB_PORT=5432
      - DB_NAME=students_registry
      - DB_USER=postgres
      - DB_PASSWORD=admin
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

  postgres:
    container_name: my-postgres-container
    image: postgres:14.5
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=students_registry
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  frontend:
    container_name: my-frontend-container
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    volumes:
      - ./frontend:/app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: