definitions:
  handlers.Department:
    properties:
      faculty_id:
        type: integer
      head_name:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  handlers.DepartmentList:
    properties:
      departments:
        items:
          $ref: '#/definitions/handlers.Department'
        type: array
    type: object
  handlers.EducationLevel:
    enum:
    - bachelor
    - master
    - postgraduate
    type: string
    x-enum-varnames:
    - Bachelor
    - Master
    - PostGraduate
  handlers.ErrorResponse:
    properties:
      error:
        example: Some error info
        type: string
    type: object
  handlers.Faculty:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  handlers.FacultyList:
    properties:
      faculties:
        items:
          $ref: '#/definitions/handlers.Faculty'
        type: array
    type: object
  handlers.Professor:
    properties:
      department_id:
        type: integer
      full_name:
        type: string
      id:
        type: integer
    type: object
  handlers.ProfessorList:
    properties:
      professors:
        items:
          $ref: '#/definitions/handlers.Professor'
        type: array
    type: object
  handlers.QualificationWork:
    properties:
      grade:
        type: integer
      id:
        type: integer
      name:
        type: string
      supervisor:
        type: string
      work_status:
        $ref: '#/definitions/handlers.WorkStatus'
      work_type:
        $ref: '#/definitions/handlers.WorkType'
    type: object
  handlers.Student:
    properties:
      education_level:
        $ref: '#/definitions/handlers.EducationLevel'
      faculty_name:
        type: string
      first_name:
        type: string
      group_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      patronomyc:
        type: string
    type: object
  handlers.StudentCard:
    properties:
      qualification_works:
        items:
          $ref: '#/definitions/handlers.QualificationWork'
        type: array
      student:
        $ref: '#/definitions/handlers.StudentDetailed'
    type: object
  handlers.StudentDetailed:
    properties:
      archived:
        type: boolean
      avatar:
        type: string
      department:
        type: string
      email:
        type: string
      faculty:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      patronomyc:
        type: string
      phone:
        type: string
    type: object
  handlers.StudentPage:
    properties:
      page_num:
        type: integer
      page_size:
        type: integer
      students:
        items:
          $ref: '#/definitions/handlers.Student'
        type: array
      total_pages:
        type: integer
    type: object
  handlers.WorkStatus:
    enum:
    - complete
    - in progress
    type: string
    x-enum-varnames:
    - Complete
    - InProgress
  handlers.WorkType:
    enum:
    - course
    - diploma
    - master
    - dissertation
    type: string
    x-enum-varnames:
    - CourseWork
    - DiplomaWork
    - MasterWork
    - Dissertation
info:
  contact: {}
  title: Student DataBase API
paths:
  /add_qualification_work:
    post:
      consumes:
      - application/json
      description: Добавить квалификационную работу
      parameters:
      - description: ID студента
        in: query
        name: student_id
        required: true
        type: integer
      - description: ID профессора
        in: query
        name: supervisor_id
        required: true
        type: integer
      - description: Наименование работы
        in: query
        name: name
        required: true
        type: string
      - description: Тип работы
        enum:
        - course
        - diploma
        - master
        - dissertation
        in: query
        name: work_type
        required: true
        type: string
      - description: Статус работы
        enum:
        - complete
        - in progress
        in: query
        name: work_status
        required: true
        type: string
      - description: Оценка
        in: query
        name: grade
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Добавление квалификационной работы
  /add_student:
    post:
      consumes:
      - application/json
      description: Добавление нового студента
      parameters:
      - description: Имя
        in: query
        name: name
        required: true
        type: string
      - description: Фамилия
        in: query
        name: surname
        required: true
        type: string
      - description: Отчество
        in: query
        name: patronymic
        required: true
        type: string
      - description: Номер телефона
        in: query
        name: phone_number
        type: string
      - description: Адрес электронной почты
        in: query
        name: email
        type: string
      - description: Дата рождения
        format: date
        in: query
        name: birth_date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Добавление студента
  /archive_student:
    put:
      consumes:
      - application/json
      description: Архивировать студента
      parameters:
      - default: 1
        description: ID студента
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Архивация студента
  /delete_student:
    delete:
      consumes:
      - application/json
      description: Удалить студента
      parameters:
      - default: 1
        description: ID студента
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Удаление студента
  /departments:
    get:
      consumes:
      - application/json
      description: Список кафедр
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.DepartmentList'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Список кафедр
  /faculties:
    get:
      consumes:
      - application/json
      description: Список факультетов
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.FacultyList'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Список факультетов
  /professors:
    get:
      consumes:
      - application/json
      description: Список профессоров
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.ProfessorList'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Список профессоров
  /student_card:
    get:
      consumes:
      - application/json
      description: Вывести карточку с подробной информаций о студенте
      parameters:
      - default: 1
        description: ID студента
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.StudentCard'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Карточка студента
  /students_page:
    get:
      consumes:
      - application/json
      description: Вывести спискок студентов для отображения на странице
      parameters:
      - default: 1
        description: Номер страницы
        in: query
        name: page
        type: integer
      - default: 20
        description: Число студентов на странице
        in: query
        name: pageSize
        type: integer
      - collectionFormat: csv
        description: Фильтрация по ID кафедры
        in: query
        items:
          type: integer
        name: depatmentId
        type: array
      - collectionFormat: csv
        description: Фильтрация по ID факультета
        in: query
        items:
          type: integer
        name: facultyIds
        type: array
      - collectionFormat: csv
        description: Фильтрация по номеру курса
        in: query
        items:
          type: integer
        name: course
        type: array
      - default: '"ASC"'
        description: Порядок сортировки
        enum:
        - ASC
        - DESC
        in: query
        name: order
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.StudentPage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Список студентов
  /update_student:
    put:
      consumes:
      - application/json
      description: Обновление информации о студенте
      parameters:
      - description: ID студента
        in: query
        name: student_id
        required: true
        type: string
      - description: ID кафедры
        in: query
        name: department_id
        type: integer
      - description: ID факультета
        in: query
        name: faculty_id
        type: integer
      - description: Имя
        in: query
        name: name
        type: string
      - description: Фамилия
        in: query
        name: surname
        type: string
      - description: Отчество
        in: query
        name: patronymic
        type: string
      - description: Год обучения
        in: query
        name: year
        type: integer
      - description: Номер группы
        in: query
        name: group
        type: integer
      - description: Номер телефона
        in: query
        name: phone_number
        type: string
      - description: Адрес электронной почты
        in: query
        name: email
        type: string
      - description: Дата рождения
        format: date
        in: query
        name: birth_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Обновление студента
swagger: "2.0"
